### ISSUE TITLE
Connect-Sonarr failing

### ISSUE THREAD

**Issue by tsgadam** [Yevrag35/PoshSonarr#103]
Hi,

I appreciate this is much more likely to be an issue on my end, considering many others must be using this fine, however I'm at a loss.

I've been using PoshSonarr for some time, however at some point my scheduled PowerShell routines have stopped working (not sure when).

When I try to manually establish a connection to the server I receive the following error:
Connect-Sonarr : Not Found at http://xxx.xxx.xxx.xxx:8989/api/system/status

For reference this was run locally on the server, though I did temporarily disable the firewall to confirm that was not an issue.

I have also set Sonarr bindings to the IP of the server, instead of the default * and that has not changed the behaviour.

I also set the authentication method on Sonarr to be External, meaning there should be no credentials issue.

I can confirm that I have another API based integration with Sonarr and that continues to work fine, meaning the server is available and the API is accessible. For reference, this is Kometa (previously Plex-Meta-Manager).

I have also used the below API testing page to confirm that it can access my server APIs and they report status 200.
https://sonarr.tv/docs/api/#/System/get_api_v3_system_status

What I did notice was that the API path shown on this testing page for System is "/api/v3/system/status" whereas when the PowerShell returns the error, the path is "/api/system/status" which is missing the v3 reference.

I have also uplifted my PowerShell install to v7 and tested again with the same results.

Having set the logging level in Sonarr to Trace, these are the log outputs for a connection attempt:
2024-12-07 09:58:03.1|Trace|Http|Req: 948 [GET] /api/system/status (from xxx.xxx.xxx.xxx)
2024-12-07 09:58:03.1|Debug|Sonarr.Http.Authentication.ApiKeyAuthenticationHandler|AuthenticationScheme: API was successfully authenticated.
2024-12-07 09:58:03.1|Trace|Http|Res: 948 [GET] /api/system/status: 404.NotFound (1 ms)
2024-12-07 09:58:03.1|Debug|Api|[GET] /api/system/status: 404.NotFound (1 ms)

Any help would be greatly appreciated and if you need any more testing/details, please let me know

Thanks in advance

Adam

**Comment by Yevrag35** [comment]
Hi Adam,
If you're using v1.4.7 of the module and using Sonarr v4+, the authors of Sonarr may have started removing the v2 API endpoints.  I've confirmed that my v1.4.7 fails as well against my Sonarr version 4 instance.

I've fallen down on maintenance, but the v2 beta version of this module does use the v3 endpoints and can confirm that it works using v2.0.0-beta.

I'll try to come back and put some more work into finalizing the beta build.  What commands were you running specifically? I can tell you if the beta module will work for you or not.

Thanks and appreciate the level of detail in your issue.

**Comment by tsgadam** [comment]
Thanks for the quick reply and pointing me at the Beta, I've got that installed and that's working for my script again :)

You're welcome on the detail, I know how much it helps for troubleshooting.

I'll look out for the next full release!
