### ISSUE TITLE
Radarr

### ISSUE THREAD

**Issue by asw13537** [Yevrag35/PoshSonarr#17]
Any plans to do module for radarr...

**Comment by Yevrag35** [comment]
I've looked a little into it, yes.  The API endpoints are laid out very similarly for both.  You can actually use this module against a Radarr instance and have it work for certain things.

I had debated including Radarr commands in this module.  But I think, at the end of the day, I'd probably make it its own standalone module.

Hell, I may even just write a script-based module for Radarr as that would be faster to write.  I did this one in C# to practice mainly.

**Comment by asw13537** [comment]
Thank you for response.

It would be good if it did have its own module. As you said, slot of
commands quote similar to donate so easy enough to test with what you have
done.

Was thinking about building some sort of IRC app, to autodownload from the
announce channels.

I know there is scripts to add to torrent client but think maybe a web app,
something along the lines of the git hub project sonarrannounce which
doesn't work.

Any how this is nice work. Thanks

**Comment by Yevrag35** [comment]
> Any how this is nice work. Thanks
No worries, it's a fun little pet project of mine.

In any event, I just wanted to let you know before I close this that I plan on creating the following starting some time when my project work load gets lighter (hopefully by May):
1. A Radarr module based on this Repo
2. A Sonarr v3 module that supports the differences between 2 and 3.

Appreciate the support!
