### ISSUE TITLE
QualityProfileId appears not to work

### ISSUE THREAD

**Issue by bifa2** [Yevrag35/PoshSonarr#8]
Hi,

When adding a series with the `-QualityProfileId` property, it appears not to work (the wrong profile is attached). The particular profile I wish to use is:

Cutoff   : 720p
Id       : 8
Items    : {0 - False, 480 - False, 480 - False, 480 - False...}
Language :
Name     : HD-720p-Cutoff-WebDL

`$Result | Add-SonarrSeries -TVDBId $Result.TVDBId -QualityProfileId 8 -RootFolderPath "E:\TV" -UseSeasonFolders` (where `$Result` comes from `Search-SonarrSeries`).

The series is added, but rather than a profile of 'HD-720p-CutOff-WebDL' being used, it's set to 'HD-1080p' which has an Id of 4.

**Comment by Yevrag35** [comment]
I'll take a look at this.  Thanks for reporting!

**Comment by Yevrag35** [comment]
Also, can you tell or show me how you got $Result?

**Comment by bifa2** [comment]
For context, I've written a simple IMDB list parsing function (as I enjoy being able to use the IMDB app to add to lists, like Radarr being able to import from the default IMDB watchlist). It returns an array of PSCustomObjects containing a title and year.

A scheduled script will run to periodically query said list, and compare against the output from Get-SonarrSeries (`$New = Compare-Object -ReferenceObject $IMDBWatchListTitles -DifferenceObject $SonarrSeries -Property Name | Where-Object { $_.SideIndicator -eq '<=' }`) and then run through and add them to Sonarr (with a bit of other logic).

The functional lines being executed are basically:

`$Series = [PSCustomObject]@{
Name = 'The Righteous Gemstones'; 
Year = 2019
}`
`$Result = Search-SonarrSeries -Name $Series.Name -Strict`

# In this instance there's more than 1 result so I refine by year:
`$Result = $Result | Where-Object { $_.Year -eq $Series.Year }`

# Now we have just one result, so attempt to add:
`$Result | Add-SonarrSeries -TVDBId $Result.TVDBId -QualityProfileId 8 -RootFolderPath "E:\TV" -UseSeasonFolders`

**Comment by Yevrag35** [comment]
Oh boy, I feel dumb.  For the source code of Add-SonarrSeries, I inadvertently hardcoded '4' for the quality profile -- see line 123 of [AddSeries.cs](https://github.com/Yevrag35/PoshSonarr/blob/master/MG.Sonarr-DotNet/Cmdlets/Series/AddSeries.cs)

I will fix that tomorrow morning.

**Comment by bifa2** [comment]
We've all been there don't worry, and thank you! As I don't know how to compile this myself (I'm fluent with PS but not with things that require compilation), what's the usual delay in getting this into the PowerShell gallery?

**Comment by Yevrag35** [comment]
Fixed and tested the solution last night.  I've published the new version right now.  Update-Module to get it like normal.

**Comment by bifa2** [comment]
Confirmed as working now. Thanks a lot :)
